language: android

sudo: false

install: true

jdk:
  - oraclejdk8

android:
  components:
  - platform-tools
  - tools

  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"

script: 
  - jdk_switcher use oraclejdk8
  - export JAVA8_HOME=$JAVA_HOME
  - $JAVA8_HOME/bin/javac -version
  - pwd
  - ./gradlew testReleaseUnitTest

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
